version: '3.8'

services:
  caliper-admin:
    image: caliper-app
    container_name: caliper_admin
    restart: unless-stopped
    ports:
      - "5011:5000"
    environment:
      - APP_MODE=ADMIN
    volumes:
      - ./data:/app/data
      - ./static/covers:/app/static/covers

  caliper-public:
    image: caliper-app
    container_name: caliper_public
    restart: unless-stopped
    ports:
      - "5010:5000"
    environment:
      - APP_MODE=PUBLIC
    volumes:
      - ./data:/app/data
      - ./static/covers:/app/static/covers